import Image from "next/image"
import { Fragment, type ReactNode } from "react"
import { assessmentCriteria, plainReviewText, reviewFeedbackItems, scoreLabel, type ReviewCommon, type ReviewRecord } from "@/lib/review-domain"
import { reportDate, type ReportArea } from "@/lib/review-report-model"
import { reviewAreaLabel, reviewCriterionLabel } from "@/lib/review-assessment-config"
import { reviewScoreExplanation } from "@/lib/review-score-policy"
import { ReviewText } from "./review-ui"
import css from "./review-report-screen.module.css"

const fmt = (n?: number) => n === undefined ? "—" : scoreLabel(n)
const palette = { first: "#aebcc7", current: "#4db9ba", final: "#0783ba" }

export function ReviewReportScreen({ common, record, first, areas }: { common: ReviewCommon; record: ReviewRecord; first?: ReviewRecord; areas: ReportArea[] }) {
  const second = record.round === 2
  const report = record.report!
  const rounds = first ? [first, record] : [record]
  const criteria = assessmentCriteria(common.level, record)
  const pageTotal = second ? 6 : 5
  const page = (number: number, title: string, children: ReactNode) => <article className={css.sheet} aria-label={title}><header className={css.runningHeader}><span>{common.studentName} · 《{common.bookTitle}》　{common.template.title}</span><span>{record.round}차 작성 완료 · {reportDate(record.submittedAt)}</span><span>{number} / {pageTotal}</span></header>{children}</article>
  return <div className={css.pages}>
    <article className={`${css.sheet} ${css.cover}`} aria-label="평가 보고서 표지"><Image src="/student-assets/dokdo-logo.svg" alt="독도" width={74} height={64} /><div><p>독후감 평가 보고서 <b>{record.round}차</b></p><h1>{common.bookTitle}</h1><h2>{common.level}레벨 · {common.template.title}</h2><dl><dt>학생명</dt><dd>{common.studentName}</dd><dt>학원명</dt><dd>{common.institution || "—"}</dd><dt>제출일</dt><dd>{reportDate(record.submittedAt)}</dd></dl></div></article>
    {page(2, "평가 결과와 총평", <><p className={css.eyebrow}>평가 결과</p><h2 className={css.title}>{second ? "글을 다시 쓰며 달라진 점" : "내 글을 함께 살펴봐요"}</h2><div className={css.scoreGrid}><section className={css.mainScore}><p>{second ? "최종 점수" : "1차 점수"}</p><strong>{fmt(second ? report.finalScore : report.score)}</strong><span> / 100점</span></section><div className={css.scoreDetails}>{second && <section><h3>작성 회차별</h3><div><small>1차 점수</small><strong>{fmt(report.firstScore)}점</strong></div><span>→</span><div><small>2차 점수</small><strong>{fmt(report.score)}점</strong></div>{(report.improvement ?? 0) > 0 && <b className={css.improvement}>+ {fmt(report.improvement)}점 향상</b>}</section>}<section><h3>평가 주체별</h3><div><small>{second ? "AI 평가 총점" : "AI 1차 점수"}</small><strong>{fmt(second ? report.weightedAi : report.ai)}점</strong></div><div><small>{second ? "선생님 평가 총점" : "선생님 1차 점수"}</small><strong>{fmt(second ? report.weightedTeacher : report.teacher)}점</strong></div></section></div></div><div className={css.explanation}><h3>평가 점수 산출 방법</h3><p>{reviewScoreExplanation(record.round)}</p></div><div className={css.comment}><h3>선생님 평가</h3><section><h4>{record.round}차 총평</h4><ReviewText value={record.reportFeedback || "저장된 총평이 없습니다."} /></section></div></>)}
    {page(3, "영역별 평가 결과", <><h2 className={css.title}>영역별 평가 결과</h2><p className={css.graphNote}>꼭짓점 숫자는 {second ? "최종" : "1차"} 성취도</p><ReportRadar areas={areas} second={second} /><p className={css.graphNote}>바깥쪽에 가까울수록 성취도가 높아요.<br />회차별 점수는 아래 표에서 확인하세요.</p><div className={css.legend}>{(second ? ["first", "current", "final"] as const : ["current"] as const).map(key => <span key={key}><i style={{background: second ? palette[key] : palette.final}} />{second ? key === "first" ? "1차" : key === "current" ? "2차" : "최종" : "1차"}</span>)}</div><table className={css.areaTable}><thead><tr><th>평가 영역</th>{second ? <><th>1차</th><th>2차</th><th>최종</th><th>1차 → 최종</th></> : <th>1차</th>}</tr></thead><tbody>{areas.map(a => <tr key={a.area}><th>{reviewAreaLabel(a.area)}</th>{(second ? ["first", "current", "final"] as const : ["current"] as const).map(key => <td key={key}><strong style={{color: second ? palette[key] : palette.final}}>{fmt(a[key] / a.max * 100)}%</strong><small>{fmt(a[key])} / {a.max}</small></td>)}{second && <td><div className={css.bars}><i style={{width:`${a.first/a.max*100}%`}} /><i style={{width:`${a.final/a.max*100}%`}} /></div></td>}</tr>)}</tbody></table></>)}
    {rounds.map((r, index) => <Fragment key={r.id}>{page(4+index, `${r.round}차 작성 글과 피드백`, <><h2 className={css.title}>{r.round}차</h2><div className={css.writingGrid}><section><header><h3>내가 쓴 글</h3><small>{reportDate(r.submittedAt)} 제출</small></header><ReviewText value={r.finalBody} /></section><section><header><h3>선생님 피드백</h3></header><h4>선생님 한마디</h4><ReviewText value={r.feedback} />{reviewFeedbackItems(common.template,r.itemFeedback).filter(f=>f.visible && plainReviewText(f.text)).map(f=><div key={f.itemId}><h4>{common.template.items.find(i=>i.id===f.itemId)?.title}</h4><ReviewText value={f.text} /></div>)}</section></div></>)}</Fragment>)}
    {page(pageTotal, "평가 기준 안내", <><h2 className={css.title}>평가 기준 안내</h2><p className={css.criteriaNote}>독후감은 아래의 기준으로 평가합니다.<br />배점은 각 기준에 부여된 점수이며, 학생이 받은 점수가 아닙니다.</p><table className={css.criteria}><thead><tr>{["평가 영역","세부 기준","평가 기준 설명","배점"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{areas.map(a=><Fragment key={a.area}>{a.details.map((c,i)=><tr key={c.id}>{i===0 && <th rowSpan={a.details.length}>{reviewAreaLabel(a.area)}</th>}<td>{reviewCriterionLabel(c)}</td><td>{c.description}</td><td>{c.max}</td></tr>)}</Fragment>)}</tbody><tfoot><tr><th colSpan={3}>총점 · 배점 합계</th><td>{criteria.reduce((sum,c)=>sum+c.max,0)}</td></tr></tfoot></table></>)}
  </div>
}

function ReportRadar({areas,second}:{areas:ReportArea[];second:boolean}) {
  const ordered = areas.length === 5 ? [areas[0],areas[4],areas[3],areas[2],areas[1]] : areas
  const point = (i:number,r:number,radius=140) => {const angle=-Math.PI/2+i*Math.PI*2/ordered.length;return {x:280+Math.cos(angle)*radius*r,y:195+Math.sin(angle)*radius*r}}
  const polygon=(ratio:number)=>ordered.map((_,i)=>{const p=point(i,ratio);return `${p.x},${p.y}`}).join(" ")
  return <svg className={css.radar} viewBox="0 0 560 390" role="img" aria-label="영역별 성취도 방사형 그래프">{[1,.8,.6,.4,.2].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke="#dae2e7" />)}{ordered.map((a,i)=>{const p=point(i,1),l=point(i,1,178);return <g key={a.area}><line x1="280" y1="195" x2={p.x} y2={p.y} stroke="#e5eaef"/><text x={l.x} y={l.y} textAnchor="middle" fill="#466579" fontSize="13">{reviewAreaLabel(a.area)}</text><text x={l.x} y={l.y+20} textAnchor="middle" fill="#087daf" fontSize="17" fontWeight="700">{fmt(a[second ? "final" : "current"]/a.max*100)}%</text></g>})}{[.2,.4,.6,.8,1].map(r=><text key={r} x="285" y={195-140*r+3} fontSize="8" fill="#91a0aa">{r*100}%</text>)}{(second ? ["first","current","final"] as const : ["current"] as const).map(key=><g key={key}><polygon points={ordered.map((a,i)=>{const p=point(i,a[key]/a.max);return `${p.x},${p.y}`}).join(" ")} fill={palette.final} fillOpacity={key==="final" || !second ? .12 : 0} stroke={second ? palette[key] : palette.final} strokeWidth={key==="final" || !second ? 2.5 : 1.8}/>{ordered.map((a,i)=>{const p=point(i,a[key]/a.max);return <circle key={a.area} cx={p.x} cy={p.y} r="3" fill={second ? palette[key] : palette.final}/>})}</g>)}</svg>
}
